version: '3'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_HOST=0.0.0.0
      - MYSQL_PORT=33060  # cannot change this port to other number
      - MYSQL_DATABASE=cgi_assignments # name you want for the database
      - MYSQL_USER="newuser" # change to whatever username you want
      - MYSQL_PASSWORD="password" #change to the password you want for user
      - MYSQL_ROOT_PASSWORD="root" #change to good root password
    ports:
      - "33060:33060"
    volumes:
      - .setup.sql:/docker-entrypoint-initbd.d/setup.sql
  
  web:
    build: .
      # command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    container_name: docker_dir
    volumes:
      - .:/docker_dir
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db 

  
